### ISSUE TITLE
Enderite Smithing templates dont spawn

### ISSUE THREAD

**Issue by Yo-Snowpro** [Yeleefff/simple-enderite-mod#2]
I have been flying in creative looking for one in a end city yet i cant even find any in the 20+ I looted

**Comment by Yeleefff** [comment]
Thanks for letting me know. I'l look into the loot table to check if its working correctly

**Comment by Yo-Snowpro** [comment]
Sounds good

**Comment by Yeleefff** [comment]
I found what I think was the issue and it should hopefully be fixed. I have pushed the changes to github and the patched version should be available on curseforge and modrinth soon (it will have to be approved first for curse, so it may take some time). Thanks again for reporting the issue

**Comment by Yo-Snowpro** [comment]
Your welcome :D
